CREATE TABLE congress2002
	(
	ROWID varchar2(255),
	FECID varchar2(255),
	STATE varchar2(255),
	DISTRICT varchar2(255),
	FIRSTNAME varchar2(255),
	LASTNAME varchar2(255),
	LASTNAMEFIRST varchar2(255),
	TOTALVOTES varchar2(255),
	PARTY varchar2(255),
	PRIMARYRESULTS varchar2(255),
	PRIMARYPCT varchar2(255),
	RUNOFFRESULTS varchar2(255),
	RUNOFFPCT varchar2(255),
	GENERALRESULTS varchar2(255),
	GENERALPCT varchar2(255),
	GENERALRUNOFFRESULTS varchar2(255),
	GENERALRUNOFFPCT varchar2(255),
	INCUMBENTINDICATOR varchar2(255),
	NOTES(SeeEndnotesPage) varchar2(255)
	);

CREATE TABLE congress2002_load
	(
	ROWID varchar2(255),
	FECID varchar2(255),
	STATE varchar2(255),
	DISTRICT varchar2(255),
	FIRSTNAME varchar2(255),
	LASTNAME varchar2(255),
	LASTNAMEFIRST varchar2(255),
	TOTALVOTES varchar2(255),
	PARTY varchar2(255),
	PRIMARYRESULTS varchar2(255),
	PRIMARYPCT varchar2(255),
	RUNOFFRESULTS varchar2(255),
	RUNOFFPCT varchar2(255),
	GENERALRESULTS varchar2(255),
	GENERALPCT varchar2(255),
	GENERALRUNOFFRESULTS varchar2(255),
	GENERALRUNOFFPCT varchar2(255),
	INCUMBENTINDICATOR varchar2(255),
	NOTES(SeeEndnotesPage) varchar2(255)
	)
ORGANIZATION EXTERNAL
	(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY ext_hoc_load
	ACCESS PARAMETERS
		(
		RECORDS DELIMITED BY NEWLINE skip=1
		fields terminated by ','
		OPTIONALLY ENCLOSED BY '"' AND '"'
		MISSING FIELD VALUES ARE NULL
		)
	LOCATION ('congress2002.csv')
	)
REJECT LIMIT UNLIMITED;

INSERT INTO congress2002
	(
	ROWID,
	FECID,
	STATE,
	DISTRICT,
	FIRSTNAME,
	LASTNAME,
	LASTNAMEFIRST,
	TOTALVOTES,
	PARTY,
	PRIMARYRESULTS,
	PRIMARYPCT,
	RUNOFFRESULTS,
	RUNOFFPCT,
	GENERALRESULTS,
	GENERALPCT,
	GENERALRUNOFFRESULTS,
	GENERALRUNOFFPCT,
	INCUMBENTINDICATOR,
	NOTES(SeeEndnotesPage)
	)
	(
	SELECT	ROWID,
		FECID,
		STATE,
		DISTRICT,
		FIRSTNAME,
		LASTNAME,
		LASTNAMEFIRST,
		TOTALVOTES,
		PARTY,
		PRIMARYRESULTS,
		PRIMARYPCT,
		RUNOFFRESULTS,
		RUNOFFPCT,
		GENERALRESULTS,
		GENERALPCT,
		GENERALRUNOFFRESULTS,
		GENERALRUNOFFPCT,
		INCUMBENTINDICATOR,
		NOTES(SeeEndnotesPage)
	FROM NHLstats_load
);