CREATE TABLE presgeneral2000
	(
	RWID varchar2(255),
	STATENAME varchar2(255),
	CANDIDATE varchar2(255),
	PARTY varchar2(255),
	NUMBEROFVOTES varchar2(255),
	COMBINEDPARTIES varchar2(255)
	);

CREATE TABLE presgeneral2000_load
	(
	RWID varchar2(255),
	STATENAME varchar2(255),
	CANDIDATE varchar2(255),
	PARTY varchar2(255),
	NUMBEROFVOTES varchar2(255),
	COMBINEDPARTIES varchar2(255)
	)
ORGANIZATION EXTERNAL
	(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY ext_hoc_load
	ACCESS PARAMETERS
		(
		RECORDS DELIMITED BY NEWLINE skip=1
		fields terminated by ','
		OPTIONALLY ENCLOSED BY '"' AND '"'
		MISSING FIELD VALUES ARE NULL
		)
	LOCATION ('presgeneral2000.csv')
	)
REJECT LIMIT UNLIMITED;

INSERT INTO presgeneral2000
	(
	RWID, STATENAME, CANDIDATE, PARTY, NUMBEROFVOTES, COMBINEDPARTIES
	)
	(
	SELECT	RWID, STATENAME, CANDIDATE, PARTY, NUMBEROFVOTES, COMBINEDPARTIES
	FROM 	presgeneral2000_load
	);

CREATE TABLE presprimary2000
	(
	RWID varchar2(255),
	STATENAME varchar2(255),
	CANDIDATE varchar2(255),
	PARTY varchar2(255),
	NUMBEROFVOTES varchar2(255),
	PERCENT varchar2(255)
	);

CREATE TABLE presprimary2000_load
	(
	RWID varchar2(255),
	STATENAME varchar2(255),
	CANDIDATE varchar2(255),
	PARTY varchar2(255),
	NUMBEROFVOTES varchar2(255),
	PERCENT varchar2(255)
	)
ORGANIZATION EXTERNAL
	(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY ext_hoc_load
	ACCESS PARAMETERS
		(
		RECORDS DELIMITED BY NEWLINE skip=1
		fields terminated by ','
		OPTIONALLY ENCLOSED BY '"' AND '"'
		MISSING FIELD VALUES ARE NULL
		)
	LOCATION ('presprimary2000.csv')
	)
REJECT LIMIT UNLIMITED;

INSERT INTO presprimary2000
	(
	RWID, STATENAME, CANDIDATE, PARTY, NUMBEROFVOTES, PERCENT
	)
	(
	SELECT
	RWID, STATENAME, CANDIDATE, PARTY, NUMBEROFVOTES, PERCENT
	FROM presprimary2000_load
	);

CREATE TABLE presprimarydates2000
	(
	RWID varchar2(255),
	STATENAME varchar2(255),
	PRIMARYDATE varchar2(255),
	CAUCUSDATE varchar2(255)
	);

CREATE TABLE presprimarydates2000_load
	(
	RWID varchar2(255),
	STATENAME varchar2(255),
	PRIMARYDATE varchar2(255),
	CAUCUSDATE varchar2(255)
	)
ORGANIZATION EXTERNAL
	(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY ext_hoc_load
	ACCESS PARAMETERS
		(
		RECORDS DELIMITED BY NEWLINE skip=1
		fields terminated by ','
		OPTIONALLY ENCLOSED BY '"' AND '"'
		MISSING FIELD VALUES ARE NULL
		)
	LOCATION ('presprimarydates2000.csv')
	)
REJECT LIMIT UNLIMITED;

INSERT INTO presprimarydates2000
	(
	RWID,STATENAME,PRIMARYDATE,CAUCUSDATE
	)
	(
	SELECT
	RWID,STATENAME,PRIMARYDATE,CAUCUSDATE
	FROM presprimarydates2000_load
	);

CREATE TABLE senate2000
	(
	RWID varchar2(255),
	STATENAME varchar2(255),
	DISTRICT varchar2(255),
	INCUMBENTINDICATOR varchar2(255),
	NAME varchar2(255),
	PARTY varchar2(255),
	PRIMARYRESULTS varchar2(255),
	RUNOFFRESULTS varchar2(255),
	GENERALRESULTS varchar2(255),
	COMBINEDPARTIES varchar2(255)
	);

CREATE TABLE senate2000_load
	(
	RWID varchar2(255),
	STATENAME varchar2(255),
	DISTRICT varchar2(255),
	INCUMBENTINDICATOR varchar2(255),
	NAME varchar2(255),
	PARTY varchar2(255),
	PRIMARYRESULTS varchar2(255),
	RUNOFFRESULTS varchar2(255),
	GENERALRESULTS varchar2(255),
	COMBINEDPARTIES varchar2(255)
	)
ORGANIZATION EXTERNAL
	(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY ext_hoc_load
	ACCESS PARAMETERS
		(
		RECORDS DELIMITED BY NEWLINE skip=1
		fields terminated by ','
		OPTIONALLY ENCLOSED BY '"' AND '"'
		MISSING FIELD VALUES ARE NULL
		)
	LOCATION ('senate2000.csv')
	)
REJECT LIMIT UNLIMITED;

INSERT INTO senate2000
	(
	RWID,STATENAME,DISTRICT,INCUMBENTINDICATOR,NAME,PARTY,PRIMARYRESULTS,RUNOFFRESULTS,GENERALRESULTS,COMBINEDPARTIES
	)
	(
	SELECT
	RWID,STATENAME,DISTRICT,INCUMBENTINDICATOR,NAME,PARTY,PRIMARYRESULTS,RUNOFFRESULTS,GENERALRESULTS,COMBINEDPARTIES
	FROM senate2000_load
	);

CREATE TABLE house2000
	(
	RWID varchar2(255),
	STATENAME varchar2(255),
	DISTRICT varchar2(255),
	INCUMBENTINDICATOR varchar2(255),
	NAME varchar2(255),
	PARTY varchar2(255),
	PRIMARYRESULTS varchar2(255),
	RUNOFFRESULTS varchar2(255),
	GENERALRESULTS varchar2(255),
	COMBINEDPARTIES varchar2(255)
	);

CREATE TABLE house2000_load
	(
	RWID varchar2(255),
	STATENAME varchar2(255),
	DISTRICT varchar2(255),
	INCUMBENTINDICATOR varchar2(255),
	NAME varchar2(255),
	PARTY varchar2(255),
	PRIMARYRESULTS varchar2(255),
	RUNOFFRESULTS varchar2(255),
	GENERALRESULTS varchar2(255),
	COMBINEDPARTIES varchar2(255)
	)
ORGANIZATION EXTERNAL
	(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY ext_hoc_load
	ACCESS PARAMETERS
		(
		RECORDS DELIMITED BY NEWLINE skip=1
		fields terminated by ','
		OPTIONALLY ENCLOSED BY '"' AND '"'
		MISSING FIELD VALUES ARE NULL
		)
	LOCATION ('house2000.csv')
	)
REJECT LIMIT UNLIMITED;

INSERT INTO house2000
	(
	RWID,STATENAME,DISTRICT,INCUMBENTINDICATOR,NAME,PARTY,PRIMARYRESULTS,RUNOFFRESULTS,GENERALRESULTS,COMBINEDPARTIES
	)
	(
	SELECT
	RWID,STATENAME,DISTRICT,INCUMBENTINDICATOR,NAME,PARTY,PRIMARYRESULTS,RUNOFFRESULTS,GENERALRESULTS,COMBINEDPARTIES
	FROM house2000_load
	);

CREATE TABLE labels2000
	(
	RWID varchar2(255),
	ABBREVIATION varchar2(255),
	EQUALS varchar2(255),
	PARTYNAME varchar2(255)
	);

CREATE TABLE labels2000_load
	(
	RWID varchar2(255),
	ABBREVIATION varchar2(255),
	EQUALS varchar2(255),
	PARTYNAME varchar2(255)
	)
ORGANIZATION EXTERNAL
	(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY ext_hoc_load
	ACCESS PARAMETERS
		(
		RECORDS DELIMITED BY NEWLINE skip=1
		fields terminated by ','
		OPTIONALLY ENCLOSED BY '"' AND '"'
		MISSING FIELD VALUES ARE NULL
		)
	LOCATION ('labels2000.csv')
	)
REJECT LIMIT UNLIMITED;

INSERT INTO labels2000
	(
	RWID,ABBREVIATION,EQUALS,PARTYNAME
	)
	(
	SELECT
	RWID,ABBREVIATION,EQUALS,PARTYNAME
	FROM labels2000_load
	);

CREATE TABLE congress2002
	(
	RWID varchar2(255),
	FECID varchar2(255),
	STATENAME varchar2(255),
	DISTRICT varchar2(255),
	FIRSTNAME varchar2(255),
	LASTNAME varchar2(255),
	LASTNAMEFIRST varchar2(255),
	TOTALVOTES varchar2(255),
	PARTY varchar2(255),
	PRIMARYRESULTS varchar2(255),
	PRIMARYPCT varchar2(255),
	RUNOFFRESULTS varchar2(255),
	RUNOFFPCT varchar2(255),
	GENERALRESULTS varchar2(255),
	GENERALPCT varchar2(255),
	GENERALRUNOFFRESULTS varchar2(255),
	GENERALRUNOFFPCT varchar2(255),
	INCUMBENTINDICATOR varchar2(255),
	NOTES varchar2(255)
	);

CREATE TABLE congress2002_load
	(
	RWID varchar2(255),
	FECID varchar2(255),
	STATENAME varchar2(255),
	DISTRICT varchar2(255),
	FIRSTNAME varchar2(255),
	LASTNAME varchar2(255),
	LASTNAMEFIRST varchar2(255),
	TOTALVOTES varchar2(255),
	PARTY varchar2(255),
	PRIMARYRESULTS varchar2(255),
	PRIMARYPCT varchar2(255),
	RUNOFFRESULTS varchar2(255),
	RUNOFFPCT varchar2(255),
	GENERALRESULTS varchar2(255),
	GENERALPCT varchar2(255),
	GENERALRUNOFFRESULTS varchar2(255),
	GENERALRUNOFFPCT varchar2(255),
	INCUMBENTINDICATOR varchar2(255),
	NOTES varchar2(255)
	)
ORGANIZATION EXTERNAL
	(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY ext_hoc_load
	ACCESS PARAMETERS
		(
		RECORDS DELIMITED BY NEWLINE skip=1
		fields terminated by ','
		OPTIONALLY ENCLOSED BY '"' AND '"'
		MISSING FIELD VALUES ARE NULL
		)
	LOCATION ('congress2002.csv')
	)
REJECT LIMIT UNLIMITED;

INSERT INTO congress2002
	(
	RWID,
	FECID,
	STATENAME,
	DISTRICT,
	FIRSTNAME,
	LASTNAME,
	LASTNAMEFIRST,
	TOTALVOTES,
	PARTY,
	PRIMARYRESULTS,
	PRIMARYPCT,
	RUNOFFRESULTS,
	RUNOFFPCT,
	GENERALRESULTS,
	GENERALPCT,
	GENERALRUNOFFRESULTS,
	GENERALRUNOFFPCT,
	INCUMBENTINDICATOR,
	NOTES
	)
	(
	SELECT	RWID,
		FECID,
		STATENAME,
		DISTRICT,
		FIRSTNAME,
		LASTNAME,
		LASTNAMEFIRST,
		TOTALVOTES,
		PARTY,
		PRIMARYRESULTS,
		PRIMARYPCT,
		RUNOFFRESULTS,
		RUNOFFPCT,
		GENERALRESULTS,
		GENERALPCT,
		GENERALRUNOFFRESULTS,
		GENERALRUNOFFPCT,
		INCUMBENTINDICATOR,
		NOTES
	FROM congress2002_load
);

CREATE TABLE labels2002
	(
	RWID varchar2(255),
	ABBREVIATION varchar2(255),
	EQUALS varchar2(255),
	PARTYNAME varchar2(255)
	);

CREATE TABLE labels2002_load
	(
	RWID varchar2(255),
	ABBREVIATION varchar2(255),
	EQUALS varchar2(255),
	PARTYNAME varchar2(255)
	)
ORGANIZATION EXTERNAL
	(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY ext_hoc_load
	ACCESS PARAMETERS
		(
		RECORDS DELIMITED BY NEWLINE skip=1
		fields terminated by ','
		OPTIONALLY ENCLOSED BY '"' AND '"'
		MISSING FIELD VALUES ARE NULL
		)
	LOCATION ('labels2002.csv')
	)
REJECT LIMIT UNLIMITED;

INSERT INTO labels2002
	(
	RWID,ABBREVIATION,EQUALS,PARTYNAME
	)
	(
	SELECT
	RWID,ABBREVIATION,EQUALS,PARTYNAME
	FROM labels2002_load
	);

CREATE TABLE primarydates2002
	(
	RWID varchar2(255),
	STATENAME varchar2(255),
	UNUSED varchar2(255),
	PRIMARYDATE varchar2(255),
	RUNOFFDATE varchar2(255)	
	);

CREATE TABLE primarydates2002_load
	(
	RWID varchar2(255),
	STATENAME varchar2(255),
	UNUSED varchar2(255),
	PRIMARYDATE varchar2(255),
	RUNOFFDATE varchar2(255)	
	)
ORGANIZATION EXTERNAL
	(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY ext_hoc_load
	ACCESS PARAMETERS
		(
		RECORDS DELIMITED BY NEWLINE skip=1
		fields terminated by ','
		OPTIONALLY ENCLOSED BY '"' AND '"'
		MISSING FIELD VALUES ARE NULL
		)
	LOCATION ('primarydates2002.csv')
	)
REJECT LIMIT UNLIMITED;

INSERT INTO primarydates2002
	(
	RWID,STATENAME,UNUSED,PRIMARYDATE,RUNOFFDATE
	)
	(
	SELECT
	RWID,STATENAME,UNUSED,PRIMARYDATE,RUNOFFDATE
	FROM primarydates2002_load
	);

CREATE TABLE presgeneral2004
	(
	RWID varchar2(255),
	IDNUMBER varchar2(255),
	FECID varchar2(255),
	STATENAME varchar2(255),
	STATENAMEABBREVIATION varchar2(255),
	GENERALELECTIONDATE varchar2(255),
	FIRSTNAME varchar2(255),
	LASTNAME varchar2(255),
	LASTNAMEFIRST varchar2(255),
	TOTALVOTES varchar2(255),
	PARTY varchar2(255),
	GENERALRESULTS varchar2(255),
	TOTALVOTESNUMBER varchar2(255),
	GENERALPCT varchar2(255),
	NOTES varchar2(255)
	);

CREATE TABLE presgeneral2004_load
	(
	RWID varchar2(255),
	IDNUMBER varchar2(255),
	FECID varchar2(255),
	STATENAME varchar2(255),
	STATENAMEABBREVIATION varchar2(255),
	GENERALELECTIONDATE varchar2(255),
	FIRSTNAME varchar2(255),
	LASTNAME varchar2(255),
	LASTNAMEFIRST varchar2(255),
	TOTALVOTES varchar2(255),
	PARTY varchar2(255),
	GENERALRESULTS varchar2(255),
	TOTALVOTESNUMBER varchar2(255),
	GENERALPCT varchar2(255),
	NOTES varchar2(255)
	)
ORGANIZATION EXTERNAL
	(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY ext_hoc_load
	ACCESS PARAMETERS
		(
		RECORDS DELIMITED BY NEWLINE skip=1
		fields terminated by ','
		OPTIONALLY ENCLOSED BY '"' AND '"'
		MISSING FIELD VALUES ARE NULL
		)
	LOCATION ('presgeneral2004.csv')
	)
REJECT LIMIT UNLIMITED;

INSERT INTO presgeneral2004
	(
	RWID,IDNUMBER,FECID,STATENAME,STATENAMEABBREVIATION,GENERALELECTIONDATE,FIRSTNAME,LASTNAME,LASTNAMEFIRST,TOTALVOTES,PARTY,GENERALRESULTS,TOTALVOTESNUMBER,GENERALPCT,NOTES
	)
	(
	SELECT	RWID,IDNUMBER,FECID,STATENAME,STATENAMEABBREVIATION,GENERALELECTIONDATE,FIRSTNAME,LASTNAME,LASTNAMEFIRST,TOTALVOTES,PARTY,GENERALRESULTS,TOTALVOTESNUMBER,GENERALPCT,NOTES
	FROM presgeneral2004_load
);

CREATE TABLE presprimary2004
	(
	RWID varchar2(255),
	IDNUMBER varchar2(255),
	FECID varchar2(255),
	STATENAME varchar2(255),
	STATENAMEABBREVIATION varchar2(255),
	PRIMARYDATE varchar2(255),
	FIRSTNAME varchar2(255),
	LASTNAME varchar2(255),
	LASTNAMEFIRST varchar2(255),
	TOTALVOTES varchar2(255),
	PARTY varchar2(255),
	PRIMARYRESULTS varchar2(255),
	PRIMARYPCT varchar2(255),
	NOTES varchar2(255)
	);

CREATE TABLE presprimary2004_load
	(
	RWID varchar2(255),
	IDNUMBER varchar2(255),
	FECID varchar2(255),
	STATENAME varchar2(255),
	STATENAMEABBREVIATION varchar2(255),
	PRIMARYDATE varchar2(255),
	FIRSTNAME varchar2(255),
	LASTNAME varchar2(255),
	LASTNAMEFIRST varchar2(255),
	TOTALVOTES varchar2(255),
	PARTY varchar2(255),
	PRIMARYRESULTS varchar2(255),
	PRIMARYPCT varchar2(255),
	NOTES varchar2(255)
	)
ORGANIZATION EXTERNAL
	(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY ext_hoc_load
	ACCESS PARAMETERS
		(
		RECORDS DELIMITED BY NEWLINE skip=1
		fields terminated by ','
		OPTIONALLY ENCLOSED BY '"' AND '"'
		MISSING FIELD VALUES ARE NULL
		)
	LOCATION ('presprimary2004.csv')
	)
REJECT LIMIT UNLIMITED;

INSERT INTO presprimary2004
	(
	RWID,IDNUMBER,FECID,STATENAME,STATENAMEABBREVIATION,PRIMARYDATE,FIRSTNAME,LASTNAME,LASTNAMEFIRST,TOTALVOTES,PARTY,PRIMARYRESULTS,PRIMARYPCT,NOTES	)
	(
	SELECT	RWID,IDNUMBER,FECID,STATENAME,STATENAMEABBREVIATION,PRIMARYDATE,FIRSTNAME,LASTNAME,LASTNAMEFIRST,TOTALVOTES,PARTY,PRIMARYRESULTS,PRIMARYPCT,NOTES
	FROM presprimary2004_load
);

CREATE TABLE congress2004
	(
	RWID varchar2(255),
	IDNUMBER varchar2(255),
	STATENAME varchar2(255),
	STATENAMEABBREVIATION varchar2(255),
	DISTRICT varchar2(255),
	FECID varchar2(255),
	INCUMBENTINDICATOR varchar2(255),
	FIRSTNAME varchar2(255),
	LASTNAME varchar2(255),
	LASTNAMEFIRST varchar2(255),
	TOTALVOTES varchar2(255),
	PARTY varchar2(255),
	PRIMARY varchar2(255),
	PRIMARYPCT varchar2(255),
	RUNOFF varchar2(255),
	RUNOFFPCT varchar2(255),
	GENERAL varchar2(255),
	GENERALPCT varchar2(255),
	GERUNOFF varchar2(255),
	GERUNOFFPCT varchar2(255),
	NOTES varchar2(255)
	);

CREATE TABLE congress2004_load
	(
	RWID varchar2(255),
	IDNUMBER varchar2(255),
	STATENAME varchar2(255),
	STATENAMEABBREVIATION varchar2(255),
	DISTRICT varchar2(255),
	FECID varchar2(255),
	INCUMBENTINDICATOR varchar2(255),
	FIRSTNAME varchar2(255),
	LASTNAME varchar2(255),
	LASTNAMEFIRST varchar2(255),
	TOTALVOTES varchar2(255),
	PARTY varchar2(255),
	PRIMARY varchar2(255),
	PRIMARYPCT varchar2(255),
	RUNOFF varchar2(255),
	RUNOFFPCT varchar2(255),
	GENERAL varchar2(255),
	GENERALPCT varchar2(255),
	GERUNOFF varchar2(255),
	GERUNOFFPCT varchar2(255),
	NOTES varchar2(255)
	)
ORGANIZATION EXTERNAL
	(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY ext_hoc_load
	ACCESS PARAMETERS
		(
		RECORDS DELIMITED BY NEWLINE skip=1
		fields terminated by ','
		OPTIONALLY ENCLOSED BY '"' AND '"'
		MISSING FIELD VALUES ARE NULL
		)
	LOCATION ('congress2004.csv')
	)
REJECT LIMIT UNLIMITED;

INSERT INTO congress2004
	(
	RWID,IDNUMBER,STATENAME,STATENAMEABBREVIATION,DISTRICT,FECID,INCUMBENTINDICATOR,FIRSTNAME,LASTNAME,LASTNAMEFIRST,TOTALVOTES,PARTY,PRIMARY,PRIMARYPCT,RUNOFF,RUNOFFPCT,GENERAL,GENERALPCT,GERUNOFF,
	GERUNOFFPCT,NOTES
	)
	(
	SELECT	RWID,IDNUMBER,STATENAME,STATENAMEABBREVIATION,DISTRICT,FECID,INCUMBENTINDICATOR,FIRSTNAME,LASTNAME,LASTNAMEFIRST,TOTALVOTES,PARTY,PRIMARY,PRIMARYPCT,RUNOFF,RUNOFFPCT,GENERAL,GENERALPCT,
	GERUNOFF,GERUNOFFPCT,NOTES
	FROM congress2004_load
);

CREATE TABLE labels2004
	(
	RWID varchar2(255),
	ABBREVIATION varchar2(255),
	EQUALS varchar2(255),
	PARTYNAME varchar2(255)
	);

CREATE TABLE labels2004_load
	(
	RWID varchar2(255),
	ABBREVIATION varchar2(255),
	EQUALS varchar2(255),
	PARTYNAME varchar2(255)
	)
ORGANIZATION EXTERNAL
	(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY ext_hoc_load
	ACCESS PARAMETERS
		(
		RECORDS DELIMITED BY NEWLINE skip=1
		fields terminated by ','
		OPTIONALLY ENCLOSED BY '"' AND '"'
		MISSING FIELD VALUES ARE NULL
		)
	LOCATION ('labels2004.csv')
	)
REJECT LIMIT UNLIMITED;

INSERT INTO labels2004
	(
	RWID,ABBREVIATION,EQUALS,PARTYNAME
	)
	(
	SELECT	RWID,ABBREVIATION,EQUALS,PARTYNAME
	FROM	labels2004_load
	);

CREATE TABLE primarydates2004
	(
	RWID varchar2(255),
	STATENAME varchar2(255),
	UNUSED varchar2(255),
	Primary varchar2(255),
	Runoff varchar2(255)	
	);

CREATE TABLE primarydates2004_load
	(
	RWID varchar2(255),
	STATENAME varchar2(255),
	UNUSED varchar2(255),
	Primary varchar2(255),
	Runoff varchar2(255)	
	)
ORGANIZATION EXTERNAL
	(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY ext_hoc_load
	ACCESS PARAMETERS
		(
		RECORDS DELIMITED BY NEWLINE skip=1
		fields terminated by ','
		OPTIONALLY ENCLOSED BY '"' AND '"'
		MISSING FIELD VALUES ARE NULL
		)
	LOCATION ('primarydates2004.csv')
	)
REJECT LIMIT UNLIMITED;

INSERT INTO primarydates2004
	(
	RWID,STATENAME,UNUSED,Primary,Runoff
	)
	(
	SELECT	RWID,STATENAME,UNUSED,Primary,Runoff
	FROM	primarydates2004_load
	);

CREATE TABLE congress2006
	(
	RWID varchar2(255),
	IDNUMBER varchar2(255),
	STATENAME varchar2(255),
	STATENAMEABBREVIATION varchar2(255),
	DISTRICT varchar2(255),
	FECID varchar2(255),
	INCUMBENTINDICATOR varchar2(255),
	FIRSTNAME varchar2(255),
	LASTNAME varchar2(255),
	LASTNAMEFIRST varchar2(255),
	TOTALVOTES varchar2(255),
	PARTY varchar2(255),
	PRIMARY varchar2(255),
	PRIMARYPCT varchar2(255),
	RUNOFF varchar2(255),
	RUNOFFPCT varchar2(255),
	GENERAL varchar2(255),
	GENERALPCT varchar2(255),
	GERUNOFF varchar2(255),
	GERUNOFFPCT varchar2(255),
	COMBINEDGEPARTYTOTALS varchar2(255),
	COMBINEDPCT varchar2(255),
	NOTES varchar2(255)
	);

CREATE TABLE congress2006_load
	(
	RWID varchar2(255),
	IDNUMBER varchar2(255),
	STATENAME varchar2(255),
	STATENAMEABBREVIATION varchar2(255),
	DISTRICT varchar2(255),
	FECID varchar2(255),
	INCUMBENTINDICATOR varchar2(255),
	FIRSTNAME varchar2(255),
	LASTNAME varchar2(255),
	LASTNAMEFIRST varchar2(255),
	TOTALVOTES varchar2(255),
	PARTY varchar2(255),
	PRIMARY varchar2(255),
	PRIMARYPCT varchar2(255),
	RUNOFF varchar2(255),
	RUNOFFPCT varchar2(255),
	GENERAL varchar2(255),
	GENERALPCT varchar2(255),
	GERUNOFF varchar2(255),
	GERUNOFFPCT varchar2(255),
	COMBINEDGEPARTYTOTALS varchar2(255),
	COMBINEDPCT varchar2(255),
	NOTES varchar2(255)
	)
ORGANIZATION EXTERNAL
	(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY ext_hoc_load
	ACCESS PARAMETERS
		(
		RECORDS DELIMITED BY NEWLINE skip=1
		fields terminated by ','
		OPTIONALLY ENCLOSED BY '"' AND '"'
		MISSING FIELD VALUES ARE NULL
		)
	LOCATION ('congress2006.csv')
	)
REJECT LIMIT UNLIMITED;

INSERT INTO congress2006
	(
	RWID,IDNUMBER,STATENAME,STATENAMEABBREVIATION,DISTRICT,FECID,INCUMBENTINDICATOR,FIRSTNAME,LASTNAME,LASTNAMEFIRST,TOTALVOTES,PARTY,PRIMARY,PRIMARYPCT,RUNOFF,RUNOFFPCT,GENERAL,GENERALPCT,GERUNOFF,
	GERUNOFFPCT,COMBINEDGEPARTYTOTALS,COMBINEDPCT,NOTES
	)
	(
	SELECT	RWID,IDNUMBER,STATENAME,STATENAMEABBREVIATION,DISTRICT,FECID,INCUMBENTINDICATOR,FIRSTNAME,LASTNAME,LASTNAMEFIRST,TOTALVOTES,PARTY,PRIMARY,PRIMARYPCT,RUNOFF,RUNOFFPCT,GENERAL,GENERALPCT,
		GERUNOFF,GERUNOFFPCT,COMBINEDGEPARTYTOTALS,COMBINEDPCT,NOTES
	FROM	congress2006_load
);

CREATE TABLE labels2006
	(
	RWID varchar2(255),
	ABBREVIATION varchar2(255),
	EQUALS varchar2(255),
	PARTYNAME varchar2(255)
	);

CREATE TABLE labels2006_load
	(
	RWID varchar2(255),
	ABBREVIATION varchar2(255),
	EQUALS varchar2(255),
	PARTYNAME varchar2(255)
	)
ORGANIZATION EXTERNAL
	(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY ext_hoc_load
	ACCESS PARAMETERS
		(
		RECORDS DELIMITED BY NEWLINE skip=1
		fields terminated by ','
		OPTIONALLY ENCLOSED BY '"' AND '"'
		MISSING FIELD VALUES ARE NULL
		)
	LOCATION ('labels2006.csv')
	)
REJECT LIMIT UNLIMITED;

INSERT INTO labels2006
	(
	RWID,ABBREVIATION,EQUALS,PARTYNAME
	)
	(
	SELECT	RWID,ABBREVIATION,EQUALS,PARTYNAME
	FROM	labels2006_load
	);

CREATE TABLE primarydates2006
	(
	RWID varchar2(255),
	STATENAME varchar2(255),
	UNUSED varchar2(255),
	Primary varchar2(255),
	Runoff varchar2(255)	
	);

CREATE TABLE primarydates2006_load
	(
	RWID varchar2(255),
	STATENAME varchar2(255),
	UNUSED varchar2(255),
	Primary varchar2(255),
	Runoff varchar2(255)	
	)
ORGANIZATION EXTERNAL
	(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY ext_hoc_load
	ACCESS PARAMETERS
		(
		RECORDS DELIMITED BY NEWLINE skip=1
		fields terminated by ','
		OPTIONALLY ENCLOSED BY '"' AND '"'
		MISSING FIELD VALUES ARE NULL
		)
	LOCATION ('primarydates2006.csv')
	)
REJECT LIMIT UNLIMITED;

INSERT INTO primarydates2006
	(
	RWID,STATENAME,UNUSED,Primary,Runoff
	)
	(
	SELECT	RWID,STATENAME,UNUSED,Primary,Runoff
	FROM	primarydates2006_load
	);

CREATE TABLE presgeneral2008
	(
	RWID varchar2(255),
	UNUSED varchar2(255),
	FECID varchar2(255),
	STATENAME varchar2(255),
	STATENAMEABBREVIATION varchar2(255),
	GENERALELECTIONDATE varchar2(255),
	FIRSTNAME varchar2(255),
	LASTNAME varchar2(255),
	LASTNAMEFIRST varchar2(255),
	TOTALVOTES varchar2(255),
	PARTY varchar2(255),
	GENERALRESULTS varchar2(255),
	TOTALVOTESNUMBER varchar2(255),
	GENERALPCT varchar2(255)
	);

CREATE TABLE presgeneral2008_load
	(
	RWID varchar2(255),
	UNUSED varchar2(255),
	FECID varchar2(255),
	STATENAME varchar2(255),
	STATENAMEABBREVIATION varchar2(255),
	GENERALELECTIONDATE varchar2(255),
	FIRSTNAME varchar2(255),
	LASTNAME varchar2(255),
	LASTNAMEFIRST varchar2(255),
	TOTALVOTES varchar2(255),
	PARTY varchar2(255),
	GENERALRESULTS varchar2(255),
	TOTALVOTESNUMBER varchar2(255),
	GENERALPCT varchar2(255)
	)
ORGANIZATION EXTERNAL
	(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY ext_hoc_load
	ACCESS PARAMETERS
		(
		RECORDS DELIMITED BY NEWLINE skip=1
		fields terminated by ','
		OPTIONALLY ENCLOSED BY '"' AND '"'
		MISSING FIELD VALUES ARE NULL
		)
	LOCATION ('presgeneral2008.csv')
	)
REJECT LIMIT UNLIMITED;

INSERT INTO presgeneral2008
	(
	RWID,UNUSED,FECID,STATENAME,STATENAMEABBREVIATION,GENERALELECTIONDATE,FIRSTNAME,LASTNAME,LASTNAMEFIRST,TOTALVOTES,PARTY,GENERALRESULTS,TOTALVOTESNUMBER,GENERALPCT
	)
	(
	SELECT	RWID,UNUSED,FECID,STATENAME,STATENAMEABBREVIATION,GENERALELECTIONDATE,FIRSTNAME,LASTNAME,LASTNAMEFIRST,TOTALVOTES,PARTY,GENERALRESULTS,TOTALVOTESNUMBER,GENERALPCT
	FROM presgeneral2008_load
);

CREATE TABLE presprimary2008
	(
	RWID varchar2(255),
	UNUSED varchar2(255),
	FECID varchar2(255),
	STATENAME varchar2(255),
	STATENAMEABBREVIATION varchar2(255),
	PRIMARYDATE varchar2(255),
	FIRSTNAME varchar2(255),
	LASTNAME varchar2(255),
	LASTNAMEFIRST varchar2(255),
	TOTALVOTES varchar2(255),
	PARTY varchar2(255),
	PRIMARYRESULTS varchar2(255),
	PRIMARYPCT varchar2(255),
	NOTES varchar2(255)
	);

CREATE TABLE presprimary2008_load
	(
	RWID varchar2(255),
	UNUSED varchar2(255),
	FECID varchar2(255),
	STATENAME varchar2(255),
	STATENAMEABBREVIATION varchar2(255),
	PRIMARYDATE varchar2(255),
	FIRSTNAME varchar2(255),
	LASTNAME varchar2(255),
	LASTNAMEFIRST varchar2(255),
	TOTALVOTES varchar2(255),
	PARTY varchar2(255),
	PRIMARYRESULTS varchar2(255),
	PRIMARYPCT varchar2(255),
	NOTES varchar2(255)
	)
ORGANIZATION EXTERNAL
	(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY ext_hoc_load
	ACCESS PARAMETERS
		(
		RECORDS DELIMITED BY NEWLINE skip=1
		fields terminated by ','
		OPTIONALLY ENCLOSED BY '"' AND '"'
		MISSING FIELD VALUES ARE NULL
		)
	LOCATION ('presprimary2008.csv')
	)
REJECT LIMIT UNLIMITED;

INSERT INTO presprimary2008
	(
	RWID,UNUSED,FECID,STATENAME,STATENAMEABBREVIATION,PRIMARYDATE,FIRSTNAME,LASTNAME,LASTNAMEFIRST,TOTALVOTES,PARTY,PRIMARYRESULTS,PRIMARYPCT,Notes
	)
	(
	SELECT	RWID,UNUSED,FECID,STATENAME,STATENAMEABBREVIATION,PRIMARYDATE,FIRSTNAME,LASTNAME,LASTNAMEFIRST,TOTALVOTES,PARTY,PRIMARYRESULTS,PRIMARYPCT,Notes
	FROM presprimary2008_load
);

CREATE TABLE congress2008
	(
	RWID varchar2(255),
	UNUSED varchar2(255),
	STATENAME varchar2(255),
	STATENAMEABBREVIATION varchar2(255),
	DISTRICT varchar2(255),
	FECID varchar2(255),
	INCUMBENTINDICATOR varchar2(255),
	CANDIDATENAMEFIRST varchar2(255),
	CANDIDATENAMELAST varchar2(255),
	CANDIDATENAME varchar2(255),
	TOTALVOTES varchar2(255),
	PARTY varchar2(255),
	PRIMARY varchar2(255),
	PRIMARYPCT varchar2(255),
	RUNOFF varchar2(255),
	RUNOFFPCT varchar2(255),
	GENERAL varchar2(255),
	GENERALPCT varchar2(255),
	GERUNOFF varchar2(255),
	GERUNOFFPCT varchar2(255),
	COMBINEDGEPARTYTOTALS varchar2(255),
	COMBINEDPCT varchar2(255),
	FOOTNOTES varchar2(255)
	);

CREATE TABLE congress2008_load
	(
	RWID varchar2(255),
	UNUSED varchar2(255),
	STATENAME varchar2(255),
	STATENAMEABBREVIATION varchar2(255),
	DISTRICT varchar2(255),
	FECID varchar2(255),
	INCUMBENTINDICATOR varchar2(255),
	CANDIDATENAMEFIRST varchar2(255),
	CANDIDATENAMELAST varchar2(255),
	CANDIDATENAME varchar2(255),
	TOTALVOTES varchar2(255),
	PARTY varchar2(255),
	PRIMARY varchar2(255),
	PRIMARYPCT varchar2(255),
	RUNOFF varchar2(255),
	RUNOFFPCT varchar2(255),
	GENERAL varchar2(255),
	GENERALPCT varchar2(255),
	GERUNOFF varchar2(255),
	GERUNOFFPCT varchar2(255),
	COMBINEDGEPARTYTOTALS varchar2(255),
	COMBINEDPCT varchar2(255),
	FOOTNOTES varchar2(255)
	)
ORGANIZATION EXTERNAL
	(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY ext_hoc_load
	ACCESS PARAMETERS
		(
		RECORDS DELIMITED BY NEWLINE skip=1
		fields terminated by ','
		OPTIONALLY ENCLOSED BY '"' AND '"'
		MISSING FIELD VALUES ARE NULL
		)
	LOCATION ('congress2008.csv')
	)
REJECT LIMIT UNLIMITED;

INSERT INTO congress2008
	(
	RWID,UNUSED,STATENAME,STATENAMEABBREVIATION,DISTRICT,FECID,INCUMBENTINDICATOR,CANDIDATENAMEFIRST,CANDIDATENAMELAST,CANDIDATENAME,TOTALVOTES,PARTY,PRIMARY,PRIMARYPCT,RUNOFF,RUNOFFPCT,GENERAL,
		GENERALPCT,GERUNOFF,GERUNOFFPCT,COMBINEDGEPARTYTOTALS,COMBINEDPCT,FOOTNOTES
	)
	(
	SELECT	RWID,UNUSED,STATENAME,STATENAMEABBREVIATION,DISTRICT,FECID,INCUMBENTINDICATOR,CANDIDATENAMEFIRST,CANDIDATENAMELAST,CANDIDATENAME,TOTALVOTES,PARTY,PRIMARY,PRIMARYPCT,RUNOFF,RUNOFFPCT,
		GENERAL,GENERALPCT,GERUNOFF,GERUNOFFPCT,COMBINEDGEPARTYTOTALS,COMBINEDPCT,FOOTNOTES
	FROM congress2008_load
);

CREATE TABLE labels2008
	(
	RWID varchar2(255),
	ABBREVIATION varchar2(255),
	EQUALS varchar2(255),
	PARTYNAME varchar2(255)
	);

CREATE TABLE labels2008_load
	(
	RWID varchar2(255),
	ABBREVIATION varchar2(255),
	EQUALS varchar2(255),
	PARTYNAME varchar2(255)
	)
ORGANIZATION EXTERNAL
	(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY ext_hoc_load
	ACCESS PARAMETERS
		(
		RECORDS DELIMITED BY NEWLINE skip=1
		fields terminated by ','
		OPTIONALLY ENCLOSED BY '"' AND '"'
		MISSING FIELD VALUES ARE NULL
		)
	LOCATION ('labels2008.csv')
	)
REJECT LIMIT UNLIMITED;

INSERT INTO labels2008
	(
	RWID,ABBREVIATION,EQUALS,PARTYNAME
	)
	(
	SELECT	RWID,ABBREVIATION,EQUALS,PARTYNAME
	FROM	labels2008_load
	);

CREATE TABLE primarydates2008
	(
	RWID varchar2(255),
	STATENAME1 varchar2(255),
	PRESIDENTIALPRIMARYDATE varchar2(255),
	PRESIDENTIALCAUCUSDATE varchar2(255),
	UNUSED varchar2(255),
	SENATEINDICATOR varchar2(255),
	STATENAME varchar2(255),
	CONGRESSIONALPRIMARYDATE varchar2(255),
	CONGRESSIONALRUNOFFDATE	 varchar2(255)
	);

CREATE TABLE primarydates2008_load
	(
	RWID varchar2(255),
	STATENAME1 varchar2(255),
	PRESIDENTIALPRIMARYDATE varchar2(255),
	PRESIDENTIALCAUCUSDATE varchar2(255),
	UNUSED varchar2(255),
	SENATEINDICATOR varchar2(255),
	STATENAME varchar2(255),
	CONGRESSIONALPRIMARYDATE varchar2(255),
	CONGRESSIONALRUNOFFDATE	 varchar2(255)
	)
ORGANIZATION EXTERNAL
	(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY ext_hoc_load
	ACCESS PARAMETERS
		(
		RECORDS DELIMITED BY NEWLINE skip=1
		fields terminated by ','
		OPTIONALLY ENCLOSED BY '"' AND '"'
		MISSING FIELD VALUES ARE NULL
		)
	LOCATION ('primarydates2008.csv')
	)
REJECT LIMIT UNLIMITED;

INSERT INTO primarydates2008
	(
	RWID,STATENAME1,PRESIDENTIALPRIMARYDATE,PRESIDENTIALCAUCUSDATE,UNUSED,SENATEINDICATOR,STATENAME,CONGRESSIONALPRIMARYDATE,CONGRESSIONALRUNOFFDATE
	)
	(
	SELECT	RWID,STATENAME1,PRESIDENTIALPRIMARYDATE,PRESIDENTIALCAUCUSDATE,UNUSED,SENATEINDICATOR,STATENAME,CONGRESSIONALPRIMARYDATE,CONGRESSIONALRUNOFFDATE
	FROM	primarydates2008_load
	);

CREATE TABLE congress2010
	(
	RWID varchar2(255),
	UNUSED varchar2(255),
	STATENAME varchar2(255),
	STATENAMEABBREVIATION varchar2(255),
	DISTRICT varchar2(255),
	FECID varchar2(255),
	INCUMBENTINDICATOR varchar2(255),
	CANDIDATENAMEFIRST varchar2(255),
	CANDIDATENAMELAST varchar2(255),
	CANDIDATENAME varchar2(255),
	TOTALVOTES varchar2(255),
	PARTY varchar2(255),
	PRIMARY varchar2(255),
	PRIMARYPCT varchar2(255),
	RUNOFF varchar2(255),
	RUNOFFPCT varchar2(255),
	GENERAL varchar2(255),
	GENERALPCT varchar2(255),
	COMBINEDGEPARTYTOTALS varchar2(255),
	COMBINEDPCT varchar2(255),
	FOOTNOTES varchar2(255)
	);

CREATE TABLE congress2010_load
	(
	RWID varchar2(255),
	UNUSED varchar2(255),
	STATENAME varchar2(255),
	STATENAMEABBREVIATION varchar2(255),
	DISTRICT varchar2(255),
	FECID varchar2(255),
	INCUMBENTINDICATOR varchar2(255),
	CANDIDATENAMEFIRST varchar2(255),
	CANDIDATENAMELAST varchar2(255),
	CANDIDATENAME varchar2(255),
	TOTALVOTES varchar2(255),
	PARTY varchar2(255),
	PRIMARY varchar2(255),
	PRIMARYPCT varchar2(255),
	RUNOFF varchar2(255),
	RUNOFFPCT varchar2(255),
	GENERAL varchar2(255),
	GENERALPCT varchar2(255),
	COMBINEDGEPARTYTOTALS varchar2(255),
	COMBINEDPCT varchar2(255),
	FOOTNOTES varchar2(255)
	)
ORGANIZATION EXTERNAL
	(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY ext_hoc_load
	ACCESS PARAMETERS
		(
		RECORDS DELIMITED BY NEWLINE skip=1
		fields terminated by ','
		OPTIONALLY ENCLOSED BY '"' AND '"'
		MISSING FIELD VALUES ARE NULL
		)
	LOCATION ('congress2010.csv')
	)
REJECT LIMIT UNLIMITED;

INSERT INTO congress2010
	(
	RWID,UNUSED,STATENAME,STATENAMEABBREVIATION,DISTRICT,FECID,INCUMBENTINDICATOR,CANDIDATENAMEFIRST,CANDIDATENAMELAST,CANDIDATENAME,TOTALVOTES,PARTY,PRIMARY,PRIMARYPCT,RUNOFF,RUNOFFPCT,GENERAL,
		GENERALPCT,COMBINEDGEPARTYTOTALS,COMBINEDPCT,FOOTNOTES
	)
	(
	SELECT	RWID,UNUSED,STATENAME,STATENAMEABBREVIATION,DISTRICT,FECID,INCUMBENTINDICATOR,CANDIDATENAMEFIRST,CANDIDATENAMELAST,CANDIDATENAME,TOTALVOTES,PARTY,PRIMARY,PRIMARYPCT,RUNOFF,RUNOFFPCT,
		GENERAL,GENERALPCT,COMBINEDGEPARTYTOTALS,COMBINEDPCT,FOOTNOTES
	FROM	congress2010_load
);

CREATE TABLE labels2010
	(
	RWID varchar2(255),
	ABBREVIATION varchar2(255),
	EQUALS varchar2(255),
	PARTYNAME varchar2(255)
	);

CREATE TABLE labels2010_load
	(
	RWID varchar2(255),
	ABBREVIATION varchar2(255),
	EQUALS varchar2(255),
	PARTYNAME varchar2(255)
	)
ORGANIZATION EXTERNAL
	(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY ext_hoc_load
	ACCESS PARAMETERS
		(
		RECORDS DELIMITED BY NEWLINE skip=1
		fields terminated by ','
		OPTIONALLY ENCLOSED BY '"' AND '"'
		MISSING FIELD VALUES ARE NULL
		)
	LOCATION ('labels2010.csv')
	)
REJECT LIMIT UNLIMITED;

INSERT INTO labels2010
	(
	RWID,ABBREVIATION,EQUALS,PARTYNAME
	)
	(
	SELECT	RWID,ABBREVIATION,EQUALS,PARTYNAME
	FROM	labels2010_load
	);

CREATE TABLE primarydates2010
	(
	RWID varchar2(255),
	STATENAME varchar2(255),
	SENATEINDICATOR varchar2(255),
	CONGRESSIONALPRIMARYDATE varchar2(255),
	CONGRESSIONALRUNOFFDATE varchar2(255)	
	);

CREATE TABLE primarydates2010_load
	(
	RWID varchar2(255),
	STATENAME varchar2(255),
	SENATEINDICATOR varchar2(255),
	CONGRESSIONALPRIMARYDATE varchar2(255),
	CONGRESSIONALRUNOFFDATE varchar2(255)	
	)
ORGANIZATION EXTERNAL
	(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY ext_hoc_load
	ACCESS PARAMETERS
		(
		RECORDS DELIMITED BY NEWLINE skip=1
		fields terminated by ','
		OPTIONALLY ENCLOSED BY '"' AND '"'
		MISSING FIELD VALUES ARE NULL
		)
	LOCATION ('primarydates2010.csv')
	)
REJECT LIMIT UNLIMITED;

INSERT INTO primarydates2010
	(
	RWID,STATENAME,SENATEINDICATOR,CONGRESSIONALPRIMARYDATE,CONGRESSIONALRUNOFFDATE
	)
	(
	SELECT	RWID,STATENAME,SENATEINDICATOR,CONGRESSIONALPRIMARYDATE,CONGRESSIONALRUNOFFDATE
	FROM	primarydates2010_load
	);

CREATE TABLE presgeneral2012
	(
	RWID varchar2(255),
	UNUSED varchar2(255),
	FECID varchar2(255),
	STATENAME varchar2(255),
	STATENAMEABBREVIATION varchar2(255),
	GENERALELECTIONDATE varchar2(255),
	FIRSTNAME varchar2(255),
	LASTNAME varchar2(255),
	LASTNAMEFIRST varchar2(255),
	TOTALVOTES varchar2(255),
	PARTY varchar2(255),
	GENERALRESULTS varchar2(255),
	TOTALVOTESNUMBER varchar2(255),
	GENERALPCT varchar2(255),
	WINNERINDICATOR varchar2(255)
	);

CREATE TABLE presgeneral2012_load
	(
	RWID varchar2(255),
	UNUSED varchar2(255),
	FECID varchar2(255),
	STATENAME varchar2(255),
	STATENAMEABBREVIATION varchar2(255),
	GENERALELECTIONDATE varchar2(255),
	FIRSTNAME varchar2(255),
	LASTNAME varchar2(255),
	LASTNAMEFIRST varchar2(255),
	TOTALVOTES varchar2(255),
	PARTY varchar2(255),
	GENERALRESULTS varchar2(255),
	TOTALVOTESNUMBER varchar2(255),
	GENERALPCT varchar2(255),
	WINNERINDICATOR varchar2(255)
	)
ORGANIZATION EXTERNAL
	(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY ext_hoc_load
	ACCESS PARAMETERS
		(
		RECORDS DELIMITED BY NEWLINE skip=1
		fields terminated by ','
		OPTIONALLY ENCLOSED BY '"' AND '"'
		MISSING FIELD VALUES ARE NULL
		)
	LOCATION ('presgeneral2012.csv')
	)
REJECT LIMIT UNLIMITED;

INSERT INTO presgeneral2012
	(
	RWID,UNUSED,FECID,STATENAME,STATENAMEABBREVIATION,GENERALELECTIONDATE,FIRSTNAME,LASTNAME,LASTNAMEFIRST,TOTALVOTES,PARTY,GENERALRESULTS,TOTALVOTESNUMBER,GENERALPCT,WINNERINDICATOR
	)
	(
	SELECT	RWID,UNUSED,FECID,STATENAME,STATENAMEABBREVIATION,GENERALELECTIONDATE,FIRSTNAME,LASTNAME,LASTNAMEFIRST,TOTALVOTES,PARTY,GENERALRESULTS,TOTALVOTESNUMBER,GENERALPCT,WINNERINDICATOR
	FROM presgeneral2012_load
);

CREATE TABLE presprimary2012
	(
	RWID varchar2(255),
	UNUSED varchar2(255),
	FECID varchar2(255),
	STATENAME varchar2(255),
	STATENAMEABBREVIATION varchar2(255),
	PRIMARYDATE varchar2(255),
	FIRSTNAME varchar2(255),
	LASTNAME varchar2(255),
	LASTNAMEFIRST varchar2(255),
	TOTALVOTES varchar2(255),
	PARTY varchar2(255),
	PRIMARYRESULTS varchar2(255),
	PRIMARYPCT varchar2(255)
	);

CREATE TABLE presprimary2012_load
	(
	RWID varchar2(255),
	UNUSED varchar2(255),
	FECID varchar2(255),
	STATENAME varchar2(255),
	STATENAMEABBREVIATION varchar2(255),
	PRIMARYDATE varchar2(255),
	FIRSTNAME varchar2(255),
	LASTNAME varchar2(255),
	LASTNAMEFIRST varchar2(255),
	TOTALVOTES varchar2(255),
	PARTY varchar2(255),
	PRIMARYRESULTS varchar2(255),
	PRIMARYPCT varchar2(255)
	)
ORGANIZATION EXTERNAL
	(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY ext_hoc_load
	ACCESS PARAMETERS
		(
		RECORDS DELIMITED BY NEWLINE skip=1
		fields terminated by ','
		OPTIONALLY ENCLOSED BY '"' AND '"'
		MISSING FIELD VALUES ARE NULL
		)
	LOCATION ('presprimary2012.csv')
	)
REJECT LIMIT UNLIMITED;

INSERT INTO presprimary2012
	(
	RWID,UNUSED,FECID,STATENAME,STATENAMEABBREVIATION,PRIMARYDATE,FIRSTNAME,LASTNAME,LASTNAMEFIRST,TOTALVOTES,PARTY,PRIMARYRESULTS,PRIMARYPCT
	)
	(
	SELECT	RWID,UNUSED,FECID,STATENAME,STATENAMEABBREVIATION,PRIMARYDATE,FIRSTNAME,LASTNAME,LASTNAMEFIRST,TOTALVOTES,PARTY,PRIMARYRESULTS,PRIMARYPCT
	FROM presprimary2012_load
);

CREATE TABLE congress2012
	(
	RWID varchar2(255),
	UNUSED varchar2(255),
	STATENAMEABBREVIATION varchar2(255),
	STATENAME varchar2(255),
	D varchar2(255),
	FECID varchar2(255),
	INCUMBENT varchar2(255),
	CANDIDATENAMEFIRST varchar2(255),
	CANDIDATENAMELAST varchar2(255),
	CANDIDATENAME varchar2(255),
	TOTALVOTES varchar2(255),
	PARTY varchar2(255),
	PRIMARYVOTES varchar2(255),
	PRIMARYPCT varchar2(255),
	RUNOFFVOTES varchar2(255),
	RUNOFFPCT varchar2(255),
	GENERALVOTES varchar2(255),
	GENERALPCT varchar2(255),
	GERUNOFFELECTIONVOTES varchar2(255),
	GERUNOFFELECTIONPCT varchar2(255),
	COMBINEDGEPARTYTOTALS varchar2(255),
	COMBINEDPCT varchar2(255),
	GEWINNERINDICATOR varchar2(255),
	FOOTNOTES varchar2(255)
	);

CREATE TABLE congress2012_load
	(
	RWID varchar2(255),
	UNUSED varchar2(255),
	STATENAMEABBREVIATION varchar2(255),
	STATENAME varchar2(255),
	D varchar2(255),
	FECID varchar2(255),
	INCUMBENT varchar2(255),
	CANDIDATENAMEFIRST varchar2(255),
	CANDIDATENAMELAST varchar2(255),
	CANDIDATENAME varchar2(255),
	TOTALVOTES varchar2(255),
	PARTY varchar2(255),
	PRIMARYVOTES varchar2(255),
	PRIMARYPCT varchar2(255),
	RUNOFFVOTES varchar2(255),
	RUNOFFPCT varchar2(255),
	GENERALVOTES varchar2(255),
	GENERALPCT varchar2(255),
	GERUNOFFELECTIONVOTES varchar2(255),
	GERUNOFFELECTIONPCT varchar2(255),
	COMBINEDGEPARTYTOTALS varchar2(255),
	COMBINEDPCT varchar2(255),
	GEWINNERINDICATOR varchar2(255),
	FOOTNOTES varchar2(255)
	)
ORGANIZATION EXTERNAL
	(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY ext_hoc_load
	ACCESS PARAMETERS
		(
		RECORDS DELIMITED BY NEWLINE skip=1
		fields terminated by ','
		OPTIONALLY ENCLOSED BY '"' AND '"'
		MISSING FIELD VALUES ARE NULL
		)
	LOCATION ('congress2012.csv')
	)
REJECT LIMIT UNLIMITED;

INSERT INTO congress2012
	(
	RWID,UNUSED,STATENAMEABBREVIATION,STATENAME,D,FECID,INCUMBENT,CANDIDATENAMEFIRST,CANDIDATENAMELAST,CANDIDATENAME,TOTALVOTES,PARTY,PRIMARYVOTES,PRIMARYPCT,RUNOFFVOTES,RUNOFFPCT,GENERALVOTES,
		GENERALPCT,GERUNOFFELECTIONVOTES,GERUNOFFELECTIONPCT,COMBINEDGEPARTYTOTALS,COMBINEDPCT,GEWINNERINDICATOR,FOOTNOTES
	)
	(
	SELECT	RWID,UNUSED,STATENAMEABBREVIATION,STATENAME,D,FECID,INCUMBENT,CANDIDATENAMEFIRST,CANDIDATENAMELAST,CANDIDATENAME,TOTALVOTES,PARTY,PRIMARYVOTES,PRIMARYPCT,RUNOFFVOTES,RUNOFFPCT,GENERALVOTES,
		GENERALPCT,GERUNOFFELECTIONVOTES,GERUNOFFELECTIONPCT,COMBINEDGEPARTYTOTALS,COMBINEDPCT,GEWINNERINDICATOR,FOOTNOTES
	FROM congress2012_load
);

CREATE TABLE labels2012
	(
	RWID varchar2(255),
	ABBREVIATION varchar2(255),
	EQUALS varchar2(255),
	PARTYNAME varchar2(255)
	);

CREATE TABLE labels2012_load
	(
	RWID varchar2(255),
	ABBREVIATION varchar2(255),
	EQUALS varchar2(255),
	PARTYNAME varchar2(255)
	)
ORGANIZATION EXTERNAL
	(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY ext_hoc_load
	ACCESS PARAMETERS
		(
		RECORDS DELIMITED BY NEWLINE skip=1
		fields terminated by ','
		OPTIONALLY ENCLOSED BY '"' AND '"'
		MISSING FIELD VALUES ARE NULL
		)
	LOCATION ('labels2012.csv')
	)
REJECT LIMIT UNLIMITED;

INSERT INTO labels2012
	(
	RWID,ABBREVIATION,EQUALS,PARTYNAME
	)
	(
	SELECT	RWID,ABBREVIATION,EQUALS,PARTYNAME
	FROM	labels2012_load
	);

CREATE TABLE primarydates2012
	(
	RWID varchar2(255),
	STATENAME1 varchar2(255),
	PRESIDENTIALPRIMARYDATE varchar2(255),
	PRESIDENTIALCAUCUSDATE varchar2(255),
	UNUSED varchar2(255),
	SENATEINDICATOR varchar2(255),
	STATENAME varchar2(255),
	CONGRESSIONALPRIMARYDATE varchar2(255),
	CONGRESSIONALRUNOFFDATE	 varchar2(255)
	);

CREATE TABLE primarydates2012_load
	(
	RWID varchar2(255),
	STATENAME1 varchar2(255),
	PRESIDENTIALPRIMARYDATE varchar2(255),
	PRESIDENTIALCAUCUSDATE varchar2(255),
	UNUSED varchar2(255),
	SENATEINDICATOR varchar2(255),
	STATENAME varchar2(255),
	CONGRESSIONALPRIMARYDATE varchar2(255),
	CONGRESSIONALRUNOFFDATE	 varchar2(255)
	)
ORGANIZATION EXTERNAL
	(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY ext_hoc_load
	ACCESS PARAMETERS
		(
		RECORDS DELIMITED BY NEWLINE skip=1
		fields terminated by ','
		OPTIONALLY ENCLOSED BY '"' AND '"'
		MISSING FIELD VALUES ARE NULL
		)
	LOCATION ('primarydates2012.csv')
	)
REJECT LIMIT UNLIMITED;

INSERT INTO primarydates2012
	(
	RWID,STATENAME1,PRESIDENTIALPRIMARYDATE,PRESIDENTIALCAUCUSDATE,UNUSED,SENATEINDICATOR,STATENAME,CONGRESSIONALPRIMARYDATE,CONGRESSIONALRUNOFFDATE
	)
	(
	SELECT	RWID,STATENAME1,PRESIDENTIALPRIMARYDATE,PRESIDENTIALCAUCUSDATE,UNUSED,SENATEINDICATOR,STATENAME,CONGRESSIONALPRIMARYDATE,CONGRESSIONALRUNOFFDATE
	FROM	primarydates2012_load
	);

CREATE TABLE house2014
	(
	RWID varchar2(255),
	UNUSED varchar2(255),
	STATENAMEABBREVIATION varchar2(255),
	STATENAME varchar2(255),
	D varchar2(255),
	FECID varchar2(255),
	INCUMBENT varchar2(255),
	CANDIDATENAMEFIRST varchar2(255),
	CANDIDATENAMELAST varchar2(255),
	CANDIDATENAME varchar2(255),
	TOTALVOTES varchar2(255),
	PARTY varchar2(255),
	PRIMARYVOTES varchar2(255),
	PRIMARYPCT varchar2(255),
	RUNOFFVOTES varchar2(255),
	RUNOFFPCT varchar2(255),
	GENERALVOTES varchar2(255),
	GENERALPCT varchar2(255),
	GERUNOFFELECTIONVOTES varchar2(255),
	GERUNOFFELECTIONPCT varchar2(255),
	COMBINEDGEPARTYTOTALS varchar2(255),
	COMBINEDPCT varchar2(255),
	GEWINNERINDICATOR varchar2(255),
	FOOTNOTES varchar2(255)
	);

CREATE TABLE house2014_load
	(
	RWID varchar2(255),
	UNUSED varchar2(255),
	STATENAMEABBREVIATION varchar2(255),
	STATENAME varchar2(255),
	D varchar2(255),
	FECID varchar2(255),
	INCUMBENT varchar2(255),
	CANDIDATENAMEFIRST varchar2(255),
	CANDIDATENAMELAST varchar2(255),
	CANDIDATENAME varchar2(255),
	TOTALVOTES varchar2(255),
	PARTY varchar2(255),
	PRIMARYVOTES varchar2(255),
	PRIMARYPCT varchar2(255),
	RUNOFFVOTES varchar2(255),
	RUNOFFPCT varchar2(255),
	GENERALVOTES varchar2(255),
	GENERALPCT varchar2(255),
	GERUNOFFELECTIONVOTES varchar2(255),
	GERUNOFFELECTIONPCT varchar2(255),
	COMBINEDGEPARTYTOTALS varchar2(255),
	COMBINEDPCT varchar2(255),
	GEWINNERINDICATOR varchar2(255),
	FOOTNOTES varchar2(255)
	)
ORGANIZATION EXTERNAL
	(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY ext_hoc_load
	ACCESS PARAMETERS
		(
		RECORDS DELIMITED BY NEWLINE skip=1
		fields terminated by ','
		OPTIONALLY ENCLOSED BY '"' AND '"'
		MISSING FIELD VALUES ARE NULL
		)
	LOCATION ('house2014.csv')
	)
REJECT LIMIT UNLIMITED;

INSERT INTO house2014
	(
	RWID,UNUSED,STATENAMEABBREVIATION,STATENAME,D,FECID,INCUMBENT,CANDIDATENAMEFIRST,CANDIDATENAMELAST,CANDIDATENAME,TOTALVOTES,PARTY,PRIMARYVOTES,PRIMARYPCT,RUNOFFVOTES,RUNOFFPCT,GENERALVOTES,GENERALPCT,
		GERUNOFFELECTIONVOTES,GERUNOFFELECTIONPCT,COMBINEDGEPARTYTOTALS,COMBINEDPCT,GEWINNERINDICATOR,FOOTNOTES
	)
	(
	SELECT	RWID,UNUSED,STATENAMEABBREVIATION,STATENAME,D,FECID,INCUMBENT,CANDIDATENAMEFIRST,CANDIDATENAMELAST,CANDIDATENAME,TOTALVOTES,PARTY,PRIMARYVOTES,PRIMARYPCT,RUNOFFVOTES,RUNOFFPCT,GENERALVOTES,
		GENERALPCT,GERUNOFFELECTIONVOTES,GERUNOFFELECTIONPCT,COMBINEDGEPARTYTOTALS,COMBINEDPCT,GEWINNERINDICATOR,FOOTNOTES
	FROM	house2014_load
);

CREATE TABLE senate2014
	(
	RWID varchar2(255),
	UNUSED varchar2(255),
	STATENAMEABBREVIATION varchar2(255),
	STATENAME varchar2(255),
	D varchar2(255),
	FECID varchar2(255),
	INCUMBENT varchar2(255),
	CANDIDATENAMEFIRST varchar2(255),
	CANDIDATENAMELAST varchar2(255),
	CANDIDATENAME varchar2(255),
	TOTALVOTES varchar2(255),
	PARTY varchar2(255),
	PRIMARYVOTES varchar2(255),
	PRIMARYPCT varchar2(255),
	RUNOFFVOTES varchar2(255),
	RUNOFFPCT varchar2(255),
	GENERALVOTES varchar2(255),
	GENERALPCT varchar2(255),
	GERUNOFFELECTIONVOTES varchar2(255),
	GERUNOFFELECTIONPCT varchar2(255),
	COMBINEDGEPARTYTOTALS varchar2(255),
	COMBINEDPCT varchar2(255),
	GEWINNERINDICATOR varchar2(255),
	FOOTNOTES varchar2(255)
	);

CREATE TABLE senate2014_load
	(
	RWID varchar2(255),
	UNUSED varchar2(255),
	STATENAMEABBREVIATION varchar2(255),
	STATENAME varchar2(255),
	D varchar2(255),
	FECID varchar2(255),
	INCUMBENT varchar2(255),
	CANDIDATENAMEFIRST varchar2(255),
	CANDIDATENAMELAST varchar2(255),
	CANDIDATENAME varchar2(255),
	TOTALVOTES varchar2(255),
	PARTY varchar2(255),
	PRIMARYVOTES varchar2(255),
	PRIMARYPCT varchar2(255),
	RUNOFFVOTES varchar2(255),
	RUNOFFPCT varchar2(255),
	GENERALVOTES varchar2(255),
	GENERALPCT varchar2(255),
	GERUNOFFELECTIONVOTES varchar2(255),
	GERUNOFFELECTIONPCT varchar2(255),
	COMBINEDGEPARTYTOTALS varchar2(255),
	COMBINEDPCT varchar2(255),
	GEWINNERINDICATOR varchar2(255),
	FOOTNOTES varchar2(255)
	)
ORGANIZATION EXTERNAL
	(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY ext_hoc_load
	ACCESS PARAMETERS
		(
		RECORDS DELIMITED BY NEWLINE skip=1
		fields terminated by ','
		OPTIONALLY ENCLOSED BY '"' AND '"'
		MISSING FIELD VALUES ARE NULL
		)
	LOCATION ('senate2014.csv')
	)
REJECT LIMIT UNLIMITED;

INSERT INTO senate2014
	(
	RWID,UNUSED,STATENAMEABBREVIATION,STATENAME,D,FECID,INCUMBENT,CANDIDATENAMEFIRST,CANDIDATENAMELAST,CANDIDATENAME,TOTALVOTES,PARTY,PRIMARYVOTES,PRIMARYPCT,RUNOFFVOTES,RUNOFFPCT,GENERALVOTES,
		GENERALPCT,GERUNOFFELECTIONVOTES,GERUNOFFELECTIONPCT,COMBINEDGEPARTYTOTALS,COMBINEDPCT,GEWINNERINDICATOR,FOOTNOTES
	)
	(
	SELECT	RWID,UNUSED,STATENAMEABBREVIATION,STATENAME,D,FECID,INCUMBENT,CANDIDATENAMEFIRST,CANDIDATENAMELAST,CANDIDATENAME,TOTALVOTES,PARTY,PRIMARYVOTES,PRIMARYPCT,RUNOFFVOTES,RUNOFFPCT,
		GENERALVOTES,GENERALPCT,GERUNOFFELECTIONVOTES,GERUNOFFELECTIONPCT,COMBINEDGEPARTYTOTALS,COMBINEDPCT,GEWINNERINDICATOR,FOOTNOTES
	FROM	senate2014_load
);


CREATE TABLE labels2014
	(
	RWID varchar2(255),
	ABBREVIATION varchar2(255),
	EQUALS varchar2(255),
	PARTYNAME varchar2(255)
	);

CREATE TABLE labels2014_load
	(
	RWID varchar2(255),
	ABBREVIATION varchar2(255),
	EQUALS varchar2(255),
	PARTYNAME varchar2(255)
	)
ORGANIZATION EXTERNAL
	(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY ext_hoc_load
	ACCESS PARAMETERS
		(
		RECORDS DELIMITED BY NEWLINE skip=1
		fields terminated by ','
		OPTIONALLY ENCLOSED BY '"' AND '"'
		MISSING FIELD VALUES ARE NULL
		)
	LOCATION ('labels2014.csv')
	)
REJECT LIMIT UNLIMITED;

INSERT INTO labels2014
	(
	RWID,ABBREVIATION,EQUALS,PARTYNAME
	)
	(
	SELECT	RWID,ABBREVIATION,EQUALS,PARTYNAME
	FROM	labels2014_load
	);

CREATE TABLE primarydates2014
	(
	RWID varchar2(255),
	UNUSED varchar2(255),
	STATENAME varchar2(255),
	CONGRESSIONALPRIMARYDATE varchar2(255),
	CONGRESSIONALRUNOFFDATE varchar2(255)	
	);

CREATE TABLE primarydates2014_load
	(
	RWID varchar2(255),
	UNUSED varchar2(255),
	STATENAME varchar2(255),
	CONGRESSIONALPRIMARYDATE varchar2(255),
	CONGRESSIONALRUNOFFDATE varchar2(255)	
	)
ORGANIZATION EXTERNAL
	(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY ext_hoc_load
	ACCESS PARAMETERS
		(
		RECORDS DELIMITED BY NEWLINE skip=1
		fields terminated by ','
		OPTIONALLY ENCLOSED BY '"' AND '"'
		MISSING FIELD VALUES ARE NULL
		)
	LOCATION ('primarydates2014.csv')
	)
REJECT LIMIT UNLIMITED;

INSERT INTO primarydates2014
	(
	RWID,UNUSED,STATENAME,CONGRESSIONALPRIMARYDATE,CONGRESSIONALRUNOFFDATE
	)
	(
	SELECT	RWID,UNUSED,STATENAME,CONGRESSIONALPRIMARYDATE,CONGRESSIONALRUNOFFDATE
	FROM	primarydates2014_load
	);

CREATE TABLE presgeneral2016
	(
	RWID varchar2(255),
	UNUSED varchar2(255),
	FECID varchar2(255),
	STATENAME varchar2(255),
	STATENAMEABBREVIATION varchar2(255),
	GENERALELECTIONDATE varchar2(255),
	FIRSTNAME varchar2(255),
	LASTNAME varchar2(255),
	LASTNAMEFIRST varchar2(255),
	TOTALVOTES varchar2(255),
	PARTY varchar2(255),
	GENERALRESULTS varchar2(255),
	TOTALVOTESNUMBER varchar2(255),
	GENERALPCT varchar2(255),
	WINNERINDICATOR varchar2(255)
	);

CREATE TABLE presgeneral2016_load
	(
	RWID varchar2(255),
	UNUSED varchar2(255),
	FECID varchar2(255),
	STATENAME varchar2(255),
	STATENAMEABBREVIATION varchar2(255),
	GENERALELECTIONDATE varchar2(255),
	FIRSTNAME varchar2(255),
	LASTNAME varchar2(255),
	LASTNAMEFIRST varchar2(255),
	TOTALVOTES varchar2(255),
	PARTY varchar2(255),
	GENERALRESULTS varchar2(255),
	TOTALVOTESNUMBER varchar2(255),
	GENERALPCT varchar2(255),
	WINNERINDICATOR varchar2(255)
	)
ORGANIZATION EXTERNAL
	(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY ext_hoc_load
	ACCESS PARAMETERS
		(
		RECORDS DELIMITED BY NEWLINE skip=1
		fields terminated by ','
		OPTIONALLY ENCLOSED BY '"' AND '"'
		MISSING FIELD VALUES ARE NULL
		)
	LOCATION ('presgeneral2016.csv')
	)
REJECT LIMIT UNLIMITED;

INSERT INTO presgeneral2016
	(
	RWID,UNUSED,FECID,STATENAME,STATENAMEABBREVIATION,GENERALELECTIONDATE,FIRSTNAME,LASTNAME,LASTNAMEFIRST,TOTALVOTES,PARTY,GENERALRESULTS,TOTALVOTESNUMBER,GENERALPCT,WINNERINDICATOR
	)
	(
	SELECT	RWID,UNUSED,FECID,STATENAME,STATENAMEABBREVIATION,GENERALELECTIONDATE,FIRSTNAME,LASTNAME,LASTNAMEFIRST,TOTALVOTES,PARTY,GENERALRESULTS,TOTALVOTESNUMBER,GENERALPCT,WINNERINDICATOR
	FROM presgeneral2016_load
);

CREATE TABLE presprimary2016
	(
	RWID varchar2(255),
	UNUSED varchar2(255),
	FECID varchar2(255),
	STATENAME varchar2(255),
	STATENAMEABBREVIATION varchar2(255),
	PRIMARYDATE varchar2(255),
	FIRSTNAME varchar2(255),
	LASTNAME varchar2(255),
	LASTNAMEFIRST varchar2(255),
	TOTALVOTES varchar2(255),
	PARTY varchar2(255),
	PRIMARYRESULTS varchar2(255),
	PRIMARYPCT varchar2(255),
	FOOTNOTES varchar2(255)
	);

CREATE TABLE presprimary2016_load
	(
	RWID varchar2(255),
	UNUSED varchar2(255),
	FECID varchar2(255),
	STATENAME varchar2(255),
	STATENAMEABBREVIATION varchar2(255),
	PRIMARYDATE varchar2(255),
	FIRSTNAME varchar2(255),
	LASTNAME varchar2(255),
	LASTNAMEFIRST varchar2(255),
	TOTALVOTES varchar2(255),
	PARTY varchar2(255),
	PRIMARYRESULTS varchar2(255),
	PRIMARYPCT varchar2(255),
	FOOTNOTES varchar2(255)
	)
ORGANIZATION EXTERNAL
	(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY ext_hoc_load
	ACCESS PARAMETERS
		(
		RECORDS DELIMITED BY NEWLINE skip=1
		fields terminated by ','
		OPTIONALLY ENCLOSED BY '"' AND '"'
		MISSING FIELD VALUES ARE NULL
		)
	LOCATION ('presprimary2016.csv')
	)
REJECT LIMIT UNLIMITED;

INSERT INTO presprimary2016
	(
	RWID,UNUSED,FECID,STATENAME,STATENAMEABBREVIATION,PRIMARYDATE,FIRSTNAME,LASTNAME,LASTNAMEFIRST,TOTALVOTES,PARTY,PRIMARYRESULTS,PRIMARYPCT,FOOTNOTES
	)
	(
	SELECT	RWID,UNUSED,FECID,STATENAME,STATENAMEABBREVIATION,PRIMARYDATE,FIRSTNAME,LASTNAME,LASTNAMEFIRST,TOTALVOTES,PARTY,PRIMARYRESULTS,PRIMARYPCT,FOOTNOTES
	FROM presprimary2016_load
);

CREATE TABLE house2016
	(
	RWID varchar2(255),
	UNUSED varchar2(255),
	STATENAMEABBREVIATION varchar2(255),
	STATENAME varchar2(255),
	D varchar2(255),
	FECID varchar2(255),
	INCUMBENT varchar2(255),
	CANDIDATENAMEFIRST varchar2(255),
	CANDIDATENAMELAST varchar2(255),
	CANDIDATENAME varchar2(255),
	TOTALVOTES varchar2(255),
	PARTY varchar2(255),
	PRIMARYVOTES varchar2(255),
	PRIMARYPCT varchar2(255),
	RUNOFFVOTES varchar2(255),
	RUNOFFPCT varchar2(255),
	GENERALVOTES varchar2(255),
	GENERALPCT varchar2(255),
	GERUNOFFELECTIONVOTES varchar2(255),
	GERUNOFFELECTIONPCT varchar2(255),
	COMBINEDGEPARTYTOTALS varchar2(255),
	COMBINEDPCT varchar2(255),
	GEWINNERINDICATOR varchar2(255),
	FOOTNOTES varchar2(255)
	);

CREATE TABLE house2016_load
	(
	RWID varchar2(255),
	UNUSED varchar2(255),
	STATENAMEABBREVIATION varchar2(255),
	STATENAME varchar2(255),
	D varchar2(255),
	FECID varchar2(255),
	INCUMBENT varchar2(255),
	CANDIDATENAMEFIRST varchar2(255),
	CANDIDATENAMELAST varchar2(255),
	CANDIDATENAME varchar2(255),
	TOTALVOTES varchar2(255),
	PARTY varchar2(255),
	PRIMARYVOTES varchar2(255),
	PRIMARYPCT varchar2(255),
	RUNOFFVOTES varchar2(255),
	RUNOFFPCT varchar2(255),
	GENERALVOTES varchar2(255),
	GENERALPCT varchar2(255),
	GERUNOFFELECTIONVOTES varchar2(255),
	GERUNOFFELECTIONPCT varchar2(255),
	COMBINEDGEPARTYTOTALS varchar2(255),
	COMBINEDPCT varchar2(255),
	GEWINNERINDICATOR varchar2(255),
	FOOTNOTES varchar2(255)
	)
ORGANIZATION EXTERNAL
	(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY ext_hoc_load
	ACCESS PARAMETERS
		(
		RECORDS DELIMITED BY NEWLINE skip=1
		fields terminated by ','
		OPTIONALLY ENCLOSED BY '"' AND '"'
		MISSING FIELD VALUES ARE NULL
		)
	LOCATION ('house2016.csv')
	)
REJECT LIMIT UNLIMITED;

INSERT INTO house2016
	(
	RWID,UNUSED,STATENAMEABBREVIATION,STATENAME,D,FECID,INCUMBENT,CANDIDATENAMEFIRST,CANDIDATENAMELAST,CANDIDATENAME,TOTALVOTES,PARTY,PRIMARYVOTES,PRIMARYPCT,RUNOFFVOTES,RUNOFFPCT,GENERALVOTES,
		GENERALPCT,GERUNOFFELECTIONVOTES,GERUNOFFELECTIONPCT,COMBINEDGEPARTYTOTALS,COMBINEDPCT,GEWINNERINDICATOR,FOOTNOTES
	)
	(
	SELECT	RWID,UNUSED,STATENAMEABBREVIATION,STATENAME,D,FECID,INCUMBENT,CANDIDATENAMEFIRST,CANDIDATENAMELAST,CANDIDATENAME,TOTALVOTES,PARTY,PRIMARYVOTES,PRIMARYPCT,RUNOFFVOTES,RUNOFFPCT,
		GENERALVOTES,GENERALPCT,GERUNOFFELECTIONVOTES,GERUNOFFELECTIONPCT,COMBINEDGEPARTYTOTALS,COMBINEDPCT,GEWINNERINDICATOR,FOOTNOTES
	FROM	house2016_load
);

CREATE TABLE senate2016
	(
	RWID varchar2(255),
	UNUSED varchar2(255),
	STATENAMEABBREVIATION varchar2(255),
	STATENAME varchar2(255),
	D varchar2(255),
	FECID varchar2(255),
	INCUMBENT varchar2(255),
	CANDIDATENAMEFIRST varchar2(255),
	CANDIDATENAMELAST varchar2(255),
	CANDIDATENAME varchar2(255),
	TOTALVOTES varchar2(255),
	PARTY varchar2(255),
	PRIMARYVOTES varchar2(255),
	PRIMARYPCT varchar2(255),
	RUNOFFVOTES varchar2(255),
	RUNOFFPCT varchar2(255),
	GENERALVOTES varchar2(255),
	GENERALPCT varchar2(255),
	GERUNOFFELECTIONVOTES varchar2(255),
	GERUNOFFELECTIONPCT varchar2(255),
	COMBINEDGEPARTYTOTALS varchar2(255),
	COMBINEDPCT varchar2(255),
	GEWINNERINDICATOR varchar2(255),
	FOOTNOTES varchar2(255)
	);

CREATE TABLE senate2016_load
	(
	RWID varchar2(255),
	UNUSED varchar2(255),
	STATENAMEABBREVIATION varchar2(255),
	STATENAME varchar2(255),
	D varchar2(255),
	FECID varchar2(255),
	INCUMBENT varchar2(255),
	CANDIDATENAMEFIRST varchar2(255),
	CANDIDATENAMELAST varchar2(255),
	CANDIDATENAME varchar2(255),
	TOTALVOTES varchar2(255),
	PARTY varchar2(255),
	PRIMARYVOTES varchar2(255),
	PRIMARYPCT varchar2(255),
	RUNOFFVOTES varchar2(255),
	RUNOFFPCT varchar2(255),
	GENERALVOTES varchar2(255),
	GENERALPCT varchar2(255),
	GERUNOFFELECTIONVOTES varchar2(255),
	GERUNOFFELECTIONPCT varchar2(255),
	COMBINEDGEPARTYTOTALS varchar2(255),
	COMBINEDPCT varchar2(255),
	GEWINNERINDICATOR varchar2(255),
	FOOTNOTES varchar2(255)
	)
ORGANIZATION EXTERNAL
	(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY ext_hoc_load
	ACCESS PARAMETERS
		(
		RECORDS DELIMITED BY NEWLINE skip=1
		fields terminated by ','
		OPTIONALLY ENCLOSED BY '"' AND '"'
		MISSING FIELD VALUES ARE NULL
		)
	LOCATION ('senate2016.csv')
	)
REJECT LIMIT UNLIMITED;

INSERT INTO senate2016
	(
	RWID,UNUSED,STATENAMEABBREVIATION,STATENAME,D,FECID,INCUMBENT,CANDIDATENAMEFIRST,CANDIDATENAMELAST,CANDIDATENAME,TOTALVOTES,PARTY,PRIMARYVOTES,PRIMARYPCT,RUNOFFVOTES,RUNOFFPCT,GENERALVOTES,
		GENERALPCT,GERUNOFFELECTIONVOTES,GERUNOFFELECTIONPCT,COMBINEDGEPARTYTOTALS,COMBINEDPCT,GEWINNERINDICATOR,FOOTNOTES
	)
	(
	SELECT	RWID,UNUSED,STATENAMEABBREVIATION,STATENAME,D,FECID,INCUMBENT,CANDIDATENAMEFIRST,CANDIDATENAMELAST,CANDIDATENAME,TOTALVOTES,PARTY,PRIMARYVOTES,PRIMARYPCT,RUNOFFVOTES,RUNOFFPCT,
		GENERALVOTES,GENERALPCT,GERUNOFFELECTIONVOTES,GERUNOFFELECTIONPCT,COMBINEDGEPARTYTOTALS,COMBINEDPCT,GEWINNERINDICATOR,FOOTNOTES
	FROM	senate2014_load
);


CREATE TABLE labels2016
	(
	RWID varchar2(255),
	ABBREVIATION varchar2(255),
	EQUALS varchar2(255),
	PARTYNAME varchar2(255)
	);

CREATE TABLE labels2016_load
	(
	RWID varchar2(255),
	ABBREVIATION varchar2(255),
	EQUALS varchar2(255),
	PARTYNAME varchar2(255)
	)
ORGANIZATION EXTERNAL
	(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY ext_hoc_load
	ACCESS PARAMETERS
		(
		RECORDS DELIMITED BY NEWLINE skip=1
		fields terminated by ','
		OPTIONALLY ENCLOSED BY '"' AND '"'
		MISSING FIELD VALUES ARE NULL
		)
	LOCATION ('labels2016.csv')
	)
REJECT LIMIT UNLIMITED;

INSERT INTO labels2016
	(
	RWID,ABBREVIATION,EQUALS,PARTYNAME
	)
	(
	SELECT	RWID,ABBREVIATION,EQUALS,PARTYNAME
	FROM	labels2016_load
	);

CREATE TABLE primarydates2016
	(
	RWID varchar2(255),
	STATENAME1 varchar2(255),
	PRESIDENTIALPRIMARYDATE varchar2(255),
	PRESIDENTIALCAUCUSDATE varchar2(255),
	UNUSED varchar2(255),
	SENATE varchar2(255),
	STATENAME varchar2(255),
	CONGRESSIONALPRIMARY varchar2(255),
	CONGRESSIONALRUNOFF varchar2(255)
	);

CREATE TABLE primarydates2016_load
	(
	RWID varchar2(255),
	STATENAME1 varchar2(255),
	PRESIDENTIALPRIMARYDATE varchar2(255),
	PRESIDENTIALCAUCUSDATE varchar2(255),
	UNUSED varchar2(255),
	SENATE varchar2(255),
	STATENAME varchar2(255),
	CONGRESSIONALPRIMARY varchar2(255),
	CONGRESSIONALRUNOFF varchar2(255)
	)
ORGANIZATION EXTERNAL
	(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY ext_hoc_load
	ACCESS PARAMETERS
		(
		RECORDS DELIMITED BY NEWLINE skip=1
		fields terminated by ','
		OPTIONALLY ENCLOSED BY '"' AND '"'
		MISSING FIELD VALUES ARE NULL
		)
	LOCATION ('dates2016.csv')
	)
REJECT LIMIT UNLIMITED;

INSERT INTO primarydates2016
	(
	RWID,STATENAME1,PRESIDENTIALPRIMARYDATE,PRESIDENTIALCAUCUSDATE,UNUSED,SENATE,STATENAME,CONGRESSIONALPRIMARY,CONGRESSIONALRUNOFF
	)
	(
	SELECT	RWID,STATENAME1,PRESIDENTIALPRIMARYDATE,PRESIDENTIALCAUCUSDATE,UNUSED,SENATE,STATENAME,CONGRESSIONALPRIMARY,CONGRESSIONALRUNOFF
	FROM	primarydates2016_load
	);